DROP TABLE TBL_LETRAS;
DROP TABLE TBL_JUEGOS;
DROP TABLE TBL_NUMEROS;
DROP TABLE TBL_LETRAS_JUEGOS;

CREATE TABLE TBL_LETRAS(
       ID INTEGER,
       LETRA CHAR
) TABLESPACE CLASE910;

CREATE TABLE TBL_JUEGOS(
       ID INTEGER
) TABLESPACE CLASE910;

ALTER TABLE tbl_juegos
ADD nombre varchar2;

CREATE TABLE TBL_NUMEROS(
       ID INTEGER,
       NUMERO INTEGER
) TABLESPACE CLASE910;

CREATE TABLE TBL_LETRAS_JUEGOS(
       ID_LETRA INTEGER,
       ID_JUEGO INTEGER,
       ID_NUMERO INTEGER
) TABLESPACE CLASE910;
