-- TBL_LETRAS
INSERT INTO TBL_LETRAS (LETRA)
  VALUES ('B');
INSERT INTO TBL_LETRAS (LETRA)
  VALUES ('I');
INSERT INTO TBL_LETRAS (LETRA)
  VALUES ('N');
INSERT INTO TBL_LETRAS (LETRA)
  VALUES ('G');
INSERT INTO TBL_LETRAS (LETRA)
  VALUES ('O');

SELECT * FROM TBL_LETRAS;


-- TBL_NUMEROS
CREATE OR REPLACE PROCEDURE insert_tbl_numeros IS
BEGIN
  FOR i IN 1..75 LOOP
      INSERT INTO TBL_NUMEROS (NUMERO) 
       VALUES (i);
       COMMIT;
  END LOOP;
END;
/
