DROP TABLE EMPLEADOS;
DROP TABLE GENEROS;
DROP TABLES DEPARTAMENTOS;

CREATE TABLE EMPLEADOS (
  IDENTIFICACION INTEGER,
  NOMBRE VARCHAR(30),
  APELLIDO_1 VARCHAR(30),
  APELLIDO_2 VARCHAR(30),
  FECHA_NACIMIENTO DATE,
  CANTIDAD_HIJOS INTEGER,
  FECHA_INGRESO DATE,
  SALARIO DOUBLE,
  ID_GENERO INTEGER,
  ID_DEPARTAMENTO INTEGER
);

CREATE TABLE GENEROS (
  IDENTIFICACION INTEGER,
  DESCRIPCION CHAR(30)
);

CREATE TABLE DEPARTAMENTOS ( 
  IDENTIFICACION INTEGER,
  DESCRIPCION VARCHAR(30)
);





