------------------------ TBL_JUEGOS

ALTER TABLE TBL_JUEGOS DROP CONSTRAINT PK_TBL_JUEGOS;
ALTER TABLE TBL_JUEGOS DROP CONSTRAINT NN_TORNEO_ID;
ALTER TABLE TBL_JUEGOS DROP CONSTRAINT TBL_TORNEOS;

ALTER TABLE TBL_JUEGOS 
  ADD CONSTRAINT PK_TBL_JUEGOS PRIMARY KEY(ID);
  
ALTER TABLE TBL_JUEGOS
  ADD CONSTRAINT NN_TORNEO_ID CHECK(TORNEO_ID IS NOT NULL) ;
  
ALTER TABLE TBL_JUEGOS
  ADD CONSTRAINT FK_TORNEO_ID FOREIGN KEY (TORNEO_ID)
  REFERENCES TBL_TORNEOS (ID);

------------------------ TBL_TORNEOS

ALTER TABLE TBL_TORNEOS DROP CONSTRAINT PK_TBL_TORNEOS;
ALTER TABLE TBL_TORNEOS DROP CONSTRAINT NN_NOMBRE_TORNEOS;
ALTER TABLE TBL_TORNEOS DROP CONSTRAINT NN_FECHA_INICIO;
ALTER TABLE TBL_TORNEOS DROP CONSTRAINT NN_FECHA_FIN;

ALTER TABLE TBL_TORNEOS
  ADD CONSTRAINT PK_TBL_TORNEOS PRIMARY KEY(ID);
  
ALTER TABLE TBL_TORNEOS
  ADD CONSTRAINT NN_NOMBRE_TORNEOS CHECK(NOMBRE IS NOT NULL);
  
ALTER TABLE TBL_TORNEOS
  ADD CONSTRAINT NN_FECHA_INICIO CHECK(FECHA_INICIO IS NOT NULL);

ALTER TABLE TBL_TORNEOS
  ADD CONSTRAINT NN_FECHA_FIN CHECK(FECHA_FIN IS NOT NULL);
  
------------------------ TBL_COMBINACIONES

ALTER TABLE TBL_COMBINACIONES DROP CONSTRAINT PK_TBL_COMBINACIONES;
ALTER TABLE TBL_COMBINACIONES DROP CONSTRAINT NN_DESCRIPCION_COMBINACIONES;

ALTER TABLE TBL_COMBINACIONES
  ADD CONSTRAINT PK_TBL_COMBINACIONES PRIMARY KEY(ID);
  
ALTER TABLE TBL_COMBINACIONES
  ADD CONSTRAINT NN_DESCRIPCION_COMBINACIONES CHECK(DESCRIPCION IS NOT NULL);
  
  
------------------------ TBL_PARTICIPANTES_JUEGOS

ALTER TABLE TBL_PARTICIPANTES_JUEGOS DROP CONSTRAINT PK_TBL_PARTICIPANTES_JUEGOS;
ALTER TABLE TBL_PARTICIPANTES_JUEGOS DROP CONSTRAINT FK_PARTICIPANTE_ID;
ALTER TABLE TBL_PARTICIPANTES_JUEGOS DROP CONSTRAINT FK_JUEGO_ID;

ALTER TABLE TBL_PARTICIPANTES_JUEGOS
  ADD CONSTRAINT PK_TBL_PARTICIPANTES_JUEGOS PRIMARY KEY(PARTICIPANTE_ID, JUEGO_ID);
  
ALTER TABLE TBL_PARTICIPANTES_JUEGOS
  ADD CONSTRAINT FK_PARTICIPANTE_ID FOREIGN KEY (PARTICIPANTE_ID)
  REFERENCES TBL_PARTICIPANTES (IDENTIFIACION);
  
ALTER TABLE TBL_PARTICIPANTES_JUEGOS
  ADD CONSTRAINT FK_JUEGO_ID FOREIGN KEY (JUEGO_ID)
  REFERENCES TBL_JUEGOS (ID);
  
------------------------ TBL_TIPO_IDENTIFICACIONES

ALTER TABLE TBL_TIPO_IDENTIFICACIONES DROP CONSTRAINT PK_TBL_TIPO_IDENTIFICACIONES;
ALTER TABLE TBL_TIPO_IDENTIFICACIONES DROP CONSTRAINT NN_DESCRIPCION_TI;

ALTER TABLE TBL_TIPO_IDENTIFICACIONES
  ADD CONSTRAINT PK_TBL_TIPO_IDENTIFICACIONES PRIMARY KEY(ID);
  
ALTER TABLE TBL_TIPO_IDENTIFICACIONES
  ADD CONSTRAINT NN_DESCRIPCION_TI CHECK(DESCRIPCION IS NOT NULL);
  
------------------------- TBL_GENEROS

ALTER TABLE TBL_TIPO_IDENTIFICACIONES DROP CONSTRAINT PK_TBL_GENEROS;
ALTER TABLE TBL_TIPO_IDENTIFICACIONES DROP CONSTRAINT NN_DESCRIPCION_GENEROS;

ALTER TABLE TBL_GENEROS
  ADD CONSTRAINT PK_TBL_GENEROS PRIMARY KEY(ID);
  
ALTER TABLE TBL_GENEROS
  ADD CONSTRAINT NN_DESCRIPCION_GENEROS CHECK(DESCRIPCION IS NOT NULL);
  

-------------------------- TBL_PARTICIPANTES

ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT PK_TBL_PARTICIPANTES;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT NN_NOMBRE_PARITICPANTE;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT NN_APELLIDO1;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT NN_FECHA_NACIMIENTO;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT NN_EMAIL;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT NN_TIPO_IDENTIFIACION_ID;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT NN_GENEROS_ID;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT U_EMAIL;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT FK_PAR_JUEG_PARJUE_ID;
ALTER TABLE TBL_PARTICIPANTES DROP CONSTRAINT FK_COMBINACIONES_ID;

ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT PK_TBL_PARTICIPANTES PRIMARY KEY(IDENTIFIACION);
  
ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT NN_NOMBRE_PARITICPANTE CHECK(NOMBRE IS NOT NULL);
   
ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT NN_APELLIDO1 CHECK(APELLIDO1 IS NOT NULL);

ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT NN_FECHA_NACIMIENTO CHECK(FECHA_NACIMIENTO IS NOT NULL);

ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT NN_EMAIL CHECK(EMAIL IS NOT NULL);
 
ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT NN_TIPO_IDENTIFIACION_ID CHECK(TIPO_IDENTIFIACION_ID IS NOT NULL);

ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT NN_GENEROS_ID CHECK(GENEROS_ID IS NOT NULL);
  
ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT U_EMAIL UNIQUE(EMAIL);
  
ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT FK_TIPO_IDENTIFIACION_ID FOREIGN KEY (TIPO_IDENTIFIACION_ID)
  REFERENCES TBL_TIPO_IDENTIFICACIONES (ID);

ALTER TABLE TBL_PARTICIPANTES
  ADD CONSTRAINT FK_GENEROS_ID FOREIGN KEY (GENEROS_ID)
  REFERENCES TBL_GENEROS (ID);
  
-------------------------- TBL_PAR_JUEG_COMBINACIONES

ALTER TABLE TBL_PAR_JUEG_COMBINACIONES DROP CONSTRAINT PK_TBL_PAR_JUEG_COMBINACIONES;
ALTER TABLE TBL_PAR_JUEG_COMBINACIONES DROP CONSTRAINT NN_COUNTER;
ALTER TABLE TBL_PAR_JUEG_COMBINACIONES DROP CONSTRAINT FK_PAR_JUEG_PARJUE_ID;
ALTER TABLE TBL_PAR_JUEG_COMBINACIONES DROP CONSTRAINT FK_COMBINACIONES_ID;

ALTER TABLE TBL_PAR_JUEG_COMBINACIONES
  ADD CONSTRAINT PK_TBL_PAR_JUEG_COMBINACIONES PRIMARY KEY(PAR_JUEG_PAR_ID, PAR_JUEG_JUEG_ID, COMBINACIONES_ID);
  
ALTER TABLE TBL_PAR_JUEG_COMBINACIONES
  ADD CONSTRAINT NN_COUNTER CHECK(COUNTER IS NOT NULL);
  
ALTER TABLE TBL_PAR_JUEG_COMBINACIONES
  ADD CONSTRAINT FK_PAR_JUEG_PARJUE_ID FOREIGN KEY (PAR_JUEG_PAR_ID, PAR_JUEG_JUEG_ID)
  REFERENCES TBL_PARTICIPANTES_JUEGOS (PARTICIPANTE_ID, JUEGO_ID);
  
ALTER TABLE TBL_PAR_JUEG_COMBINACIONES
  ADD CONSTRAINT FK_COMBINACIONES_ID FOREIGN KEY (COMBINACIONES_ID)
  REFERENCES TBL_COMBINACIONES (ID);
    
