DROP TABLE TBL_JUEGOS;
DROP TABLE TBL_TORNEOS;
DROP TABLE TBL_COMBINACIONES;
DROP TABLE TBL_PARTICIPANTES_JUEGOS;
DROP TABLE TBL_TIPO_IDENTIFICACIONES;
DROP TABLE TBL_GENEROS;
DROP TABLE TBL_PARTICIPANTES;
DROP TABLE TBL_PAR_JUEG_COMBINACIONES;

CREATE TABLE TBL_JUEGOS (
  ID INTEGER,
  TORNEO_ID INTEGER
) TABLESPACE UDPOKER;

CREATE TABLE TBL_TORNEOS(
  ID INTEGER,
  NOMBRE VARCHAR2(30),
  FECHA_INICIO DATE,
  FECHA_FIN DATE
) TABLESPACE UDPOKER;

CREATE TABLE TBL_COMBINACIONES(
  ID INTEGER,
  DESCRIPCION VARCHAR(30)
) TABLESPACE UDPOKER;

CREATE TABLE TBL_PARTICIPANTES_JUEGOS(
  PARTICIPANTE_ID VARCHAR2(60),
  JUEGO_ID INTEGER
) TABLESPACE UDPOKER;

CREATE TABLE TBL_TIPO_IDENTIFICACIONES(
  ID INTEGER,
  DESCRIPCION VARCHAR2(30)
) TABLESPACE UDPOKER;

CREATE TABLE TBL_GENEROS(
  ID INTEGER,
  DESCRIPCION VARCHAR2(30)
) TABLESPACE UDPOKER;

CREATE TABLE TBL_PARTICIPANTES(
  IDENTIFIACION VARCHAR2(60),
  NOMBRE VARCHAR2(30),
  APELLIDO1 VARCHAR2(30),
  APELLIDO2 VARCHAR2(30),
  FECHA_NACIMIENTO DATE,
  EMAIL VARCHAR2(60),
  TIPO_IDENTIFIACION_ID INTEGER,
  GENEROS_ID INTEGER
) TABLESPACE UDPOKER;

CREATE TABLE TBL_PAR_JUEG_COMBINACIONES(
  COUNTER INTEGER,
  PAR_JUEG_PAR_ID VARCHAR2(60),
  PAR_JUEG_JUEG_ID INTEGER,
  COMBINACIONES_ID INTEGER
) TABLESPACE UDPOKER;




